# Generated by Django 3.2.6 on 2021-08-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('no_files', models.IntegerField(default=0)),
                ('enrollment_time', models.FloatField(default=0.0)),
            ],
        ),
    ]
