# Generated by Django 3.2.6 on 2021-08-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1)),
                ('about_me', models.TextField()),
                ('marital_status', models.CharField(max_length=20)),
                ('hobbies', models.TextField()),
                ('profile_iris_image', models.ImageField(upload_to='profile_iris_image/')),
                ('profileMatFileName', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
