# Generated by Django 3.2.6 on 2021-08-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0005_alter_profile_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileMatFileName',
            field=models.CharField(blank=True, help_text='Leave this blank', max_length=20),
        ),
    ]
