# Generated by Django 3.2.6 on 2021-08-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_alter_profile_profilematfilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=6),
        ),
    ]
